services:
  api:
    build: .
    tty: true
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/src/
      - ./tests/:/app/tests/
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16
    container_name: notes-db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: